Only proceed if a tag can be checked out

diff --git a/bin/mkrelease b/bin/mkrelease
--- a/bin/mkrelease
+++ b/bin/mkrelease
@@ -7,28 +7,31 @@ VERSION=$1
 TAG=v$VERSION
 DIR=release/$TAG
 SUCCEED=0
+BRANCH=`git branch | grep \* | sed -e 's/\*//' | sed -e 's/[[:space:]]*//g'`
 
-git stash -q
-REV=`git rev-parse HEAD`
+git checkout -q $TAG 1>/dev/null 2>&1
 
-git checkout -q $TAG
+if [[ $? -ne 0 ]]; then
+  echo "ERROR: can not check out tag of the version specified"
+  exit
+fi
+
 mkdir -p release/$TAG
-if [[ `grep $VERSION xmml.dtd | wc -l` -gt 0 ]]; then
+if [[ `grep \"$VERSION\" xmml.dtd | wc -l` -gt 0 ]]; then
 	cp xmml.dtd $DIR/xmml-$VERSION.dtd
 else
 	echo "WARNING: xMML Document Type Definition does not match version of Git repository"
 	SUCCEED=1
 fi
 
-if [[ `grep $VERSION xMML.xsd.xml | wc -l` -gt 0 ]]; then
+if [[ `grep \"$VERSION\" xMML.xsd.xml | wc -l` -gt 0 ]]; then
 	cp xMML.xsd.xml $DIR/xMML-$VERSION.xsd.xml
 else
 	echo "WARNING: xMML Schema Definition does not match version of Git repository"
 	SUCCEED=1
 fi
 
-git checkout -q $REV
-git stash pop -q
+git checkout -q $BRANCH
 
 if [[ $SUCCEED -eq 0 ]]; then
 	echo "Release $VERSION created in directory $DIR"
